config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "meetings#index"

  resources :meetings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :invitee, class_name: "User", foreign_key: 'invitee_id'

  validates_presence_of :tokbox_session_id
  before_validation :generate_opentok_session, if: -> { new_record? }

  def generate_opentok_session
    opentok_service = OpentokService.new
    result, _error = opentok_service.create_session
    if result.present?
      self.tokbox_session_id = result.session_id
    end
  end

  def generate_opentok_token
    opentok_service = OpentokService.new
    result, error = opentok_service.generate_token(self.tokbox_session_id, opts = {
      role:                      :moderator,
      expire_time:               Time.now.to_i + (60 * 60), # in one hours
      data:                      "email=#{user.email}",
      initial_layout_class_list: %w[focus inactive],
    })
    result
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meetings, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :find_meeting, only: %i[show edit update destroy] 

  def index
    @meetings = Meeting.where("user_id = ? OR invitee_id = ?", current_user.id, current_user.id).order('created_at DESC')
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = current_user.meetings.new(meeting_params)
    if @meeting.save
      redirect_to(meetings_path)
    else
      render(:new)
    end
  end

  def show
    @token = @meeting.generate_opentok_token
    if @token.blank?
      redirect_to(meetings_path)
    end
  end

  def edit;  end

  def update
    if @meeting.update(meeting_params)
      redirect_to(meetings_path)
    else
      render(:edit)
    end
  end

  def destroy
    if @meeting.destroy
      redirect_to(meetings_path)
    else
      redirect_to(meetings_path)
    end
  end

  private

  def meeting_params
     params.require(:meeting).permit(:title, :description, :invitee_id)
  end

  def find_meeting
    @meeting = Meeting.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Video Call Rails App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">

        <%if user_signed_in?%>
          <li class="nav-item">
            <%=link_to "New Meeting", new_meeting_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%=link_to "All Meetings", meetings_path, class: "nav-link"%>
          </li>
        <%end%>

        <% unless user_signed_in?%>
          <li class="nav-item">
            <%=link_to "Signup", new_user_registration_path, class: 'nav-link'%>
          </li>
        <%end%>

        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <% else %>
            <%=link_to "Login", new_user_session_path, class: 'nav-link'%>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video Call RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <!-- <div class="container">     -->
      <%= yield %>
    <!-- </div> -->
    <%= render 'layouts/footer'%>   
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_for @meeting do |f| %>
  <div class="form-group">
    <label>Title*</label>
    <%= f.text_field :title, placeholder: "Title", required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description*</label>
    <%= f.text_area :description, placeholder: "Description", required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Meeting User*</label>
    <%=f.select :invitee_id, options_for_select(User.where.not(id: current_user.id).pluck(:email, :id), f.object.invitee_id), {include_blank: "---- Select Meeting User--- "}, { class: "form-control", required: true} %>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-primary" >Save</button>
    <%= link_to 'Back', meetings_path, class: "btn btn-primary" %>
  </div>
<%end%>

app/views/meetings/_video_actions.html.erb
<div class="video_btns_wrap">
  <!-- Audio ON/OFF -->
  <%= link_to "javascript:void(0);", class: 'microphone audio-on' do%>
    <%= image_tag 'microphone.svg'%>
  <%end%>
  <%= link_to "javascript:void(0);", class: 'microphone audio-off', style: "display: none;" do%>
    <%=  image_tag 'microphone_slash.svg'%>
  <%end%>
  <!-- Audio ON/OFF -->

  <!-- Video ON/OFF -->
  <%= link_to "javascript:void(0);", class: "video video-on" do %>
    <%= image_tag 'video.svg'%>
  <%end%>
  <%= link_to "javascript:void(0);", class: "video video-off", style: "display: none;" do %>
    <%= image_tag 'video_off.svg'%>
  <%end%>   
  <!-- Video ON/OFF -->

  <%= link_to "javascript:void(0);", class: 'call_drop_icon' do%>
    <%= image_tag 'call_icon.svg'%>
  <%end%>
</div>

app/views/meetings/edit.html.erb
<div class="container" style="margin-top: 80px;">
  <div class="row">
  <div class="col-md-6">
    <h3>Edit Meeting</h3>
    <%= render 'form' %>
  </div>
  </div>
</div>

app/views/meetings/index.html.erb
<div class="container">
  <div style= "margin-top: 80px;">
    <div class="create_meeting">
      <% if current_user.present? %>
        <%=link_to "New Meeting", new_meeting_path, class: 'btn btn-outline-primary'%>
      <% end %>
    </div>
    <h2>Meeting List</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Title</th>
          <th scope="col">Meeting User</th>
          <th scope="col">Description</th>
          <th scope="col">Meeting Link</th>
        </tr>
      </thead>
      <tbody>
        <%unless @meetings.blank?%>
          <% @meetings.each do |meeting| %>
            <tr>
              <td><%= meeting.id %></td>
              <td><%= meeting.title %></td>
              <td><%= meeting&.invitee&.email %></td>
              <td><%= truncate(meeting.description, length: 50, ommission: "...") %></td>
              <td><%=link_to "#{meeting_path(meeting)}", meeting_path(meeting)%></td>
              <% if current_user.present? && current_user.eql?(meeting.user)%>
                <td><%= link_to "Edit", edit_meeting_path(meeting) %></td>
                <td><%= link_to "Delete", meeting_path(meeting), method: :delete, data: {confirm: "Are you sure?"} %></td>
              <% end %>
            </tr>
          <% end%>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/meetings/new.html.erb
<div class="container" style="margin-top: 80px;">
  <div class="row">
  <div class="col-md-6">
    <h3>Create Meeting</h3>
    <%= render 'form' %>
  </div>
  </div>
</div>

app/views/meetings/show.html.erb
<script src="https://static.opentok.com/v2/js/opentok.min.js"></script>

<div class="video_chat_wrapper">
  <div class="videos">
    <div class="publisher" id="publisher"></div>
    <div class="subscriber grid4" id="subscribers"></div>
    <%= render 'video_actions'%>
  </div>
</div>

<script type="text/javascript">
  // declare empty global session variable
  var subscribers = document.getElementById("subscribers");
  var api_key = "<%=ENV['TOKBOX_API_KEY']%>";
  var session_id = "<%=@meeting.tokbox_session_id%>";
  var token = "<%=@token%>";
  var session = '';

  // reload page to render with variables
  (function() {
    if(window.localStorage) {
      if(!localStorage.getItem('firstLoad')) {
        localStorage['firstLoad'] = true;
        window.location.reload();
    } else
      localStorage.removeItem('firstLoad');
    }
  })();

  document.addEventListener('DOMContentLoaded', function() {
    // Initialize an OpenTok Session object
    if(session == '') {
      session = OT.initSession(api_key, session_id);
    }

    session.on({
      // This function runs when session.connect() asynchronously completes
      sessionConnected: function(event) {
        session.publish(videoPublisher, function(error) {
          if (error) {
            console.error('Failed to publish', error);
          }
        });
      },

      // This function runs when another client publishes a stream (eg. session.publish())
      streamCreated: function(event) {
        session.subscribe(event.stream, "subscribers", {
          insertMode: 'append',
          width: "100%",
          height: "100%"
        }, function(error) {
          if (error) {
            console.error('Failed to subscribe', error);
          }else{
            // if(event.stream.videoType === "video"){
            //   // Screen/video share subscribed successfully!
            // }
          }
        });
      },

      sessionDisconnected: function(event){
        window.location = "<%=meetings_path%>";
      },
      streamPropertyChanged: function(event){
        if(event.stream.connection.connectionId === session.connection.connectionId){
          // Handle audio action buttons
          if(event.stream.hasAudio){
            $('.audio-off').hide();
            $('.audio-on').show();
          }else{
            $('.audio-on').hide();
            $('.audio-off').show();
          }
          // Handle video action buttons
          if(event.stream.hasVideo){
            $('.video-off').hide();
            $('.video-on').show();
          }else{
            $('.video-on').hide();
            $('.video-off').show();
          }
        }
      }      
    });

    // Connect to the Session using a 'token'
    session.connect(token, function(error) {
      if (error) {
        if(error.name === 'OT_AUTHENTICATION_ERROR'){
          alert('Failed to connect: Token Expired');
        }else{
          alert('Failed to connect', error.name);
        }
        window.location = "<%=meetings_path%>";
      }
    });

    //Disconnect to session
    $('.call_drop_icon').on('click', function(){
      session.disconnect(event, function(){
        if (error){
          console.error('Failed to connect', error);
        }
      })
    });

    // Publisher Audio ON
    $('.audio-off').click(function(){
      videoPublisher.publishAudio(true);
    });

    // Publisher Audio OFF
    $('.audio-on').click(function(){
      videoPublisher.publishAudio(false);
    });

    // Publisher Video ON
    $('.video-off').click(function(){
      videoPublisher.publishVideo(true);
    });

    // Publisher Video OFF
    $('.video-on').click(function(){
      videoPublisher.publishVideo(false);
    });


    var videoPublisher = OT.initPublisher('publisher', {
      insertMode: 'append',
      width: '100%',
      height: '100%'
    }, function(error){
      if(error){
        console.error('Failed to initialise publisher', error);
      };
    });
  });
</script>